# Generated by Django 3.2.8 on 2021-10-15 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0009_alter_comment_options'),
        ('users', '0008_auto_20211013_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_posts',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='instagram.post'),
            preserve_default=False,
        ),
    ]
