# Generated by Django 3.2.8 on 2021-10-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_bg_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
