# Generated by Django 3.2.8 on 2021-11-17 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20211117_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatdialog',
            name='slug',
        ),
        migrations.AddField(
            model_name='chatdialog',
            name='dname',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
