# Generated by Django 3.2.8 on 2021-11-17 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_auto_20211117_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='related_chat',
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages_recieved', to='auth.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ChatDialog',
        ),
    ]
