# Generated by Django 3.2.8 on 2021-11-17 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20211117_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='related_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat'),
        ),
    ]
