# Generated by Django 3.2.8 on 2021-10-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20211012_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='defaul.jpg', upload_to='post_pics'),
        ),
    ]
