# Generated by Django 3.2.8 on 2021-10-14 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
