# Generated by Django 3.2.8 on 2021-10-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0008_remove_post_likes_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
