# Generated by Django 3.2.8 on 2021-10-18 09:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0010_auto_20211017_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), default=list, size=None),
        ),
    ]
